name: azkar
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0

  rxdart: ^0.24.1
  path_provider: ^1.6.11
  http: ^0.12.1
  audioplayers: ^0.16.1
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/elwrd.mp3
    - assets/BGG.gif

    




  fonts: 
    - family: Kufam
      fonts:
        - asset: assets/fonts/Kufam/static/Kufam-Bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Rakkas
      fonts:
        - asset: assets/fonts/Rakkas/Rakkas-Regular.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster/Lobster-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
